import { Node, mergeAttributes } from '@tiptap/core';
import markdownItFootnote from 'markdown-it-footnote';

/**
 * FootnoteSep - Captures the <hr class="footnotes-sep"> that markdown-it-footnote
 * generates before the footnotes section. This node serializes to NOTHING,
 * preventing the <hr> from accumulating as extra "---" on each save cycle.
 */
export const FootnoteSep = Node.create({
  name: 'footnoteSep',
  group: 'block',
  atom: true,

  parseHTML() {
    return [
      {
        tag: 'hr.footnotes-sep',
        priority: 300, // Higher than default horizontalRule
      },
    ];
  },

  renderHTML() {
    // Render as invisible element
    return ['div', { style: 'display:none', class: 'footnote-sep' }];
  },

  addStorage() {
    return {
      markdown: {
        serialize() {
          // Intentionally empty - this separator is auto-generated by markdown-it
        },
      },
    };
  },
});

/**
 * FootnoteReference - Inline node representing [^id] in the text body.
 * Renders as a clickable superscript number.
 */
export const FootnoteReference = Node.create({
  name: 'footnoteReference',
  inline: true,
  group: 'inline',
  atom: true,

  addAttributes() {
    return {
      id: {
        default: '1',
        parseHTML: element => {
          const href = element.querySelector('a')?.getAttribute('href') || element.getAttribute('href');
          if (href && href.startsWith('#fn')) {
            return href.substring(3);
          }
          const refId = element.getAttribute('data-footnote-ref-id');
          if (refId) return refId;
          return element.textContent?.replace(/[\[\]^]/g, '') || '1';
        },
      },
    };
  },

  parseHTML() {
    return [
      {
        tag: 'sup.footnote-ref',
        priority: 200,
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'sup',
      mergeAttributes(HTMLAttributes, {
        class: 'footnote-ref',
        'data-footnote-ref-id': HTMLAttributes.id,
      }),
      `[${HTMLAttributes.id}]`,
    ];
  },

  addStorage() {
    return {
      markdown: {
        serialize(state: any, node: any) {
          state.write(`[^${node.attrs.id}]`);
        },
        parse: {
          setup(markdownit: any) {
            if (!markdownit.__hasFootnotePlugin) {
              markdownit.use(markdownItFootnote);
              markdownit.__hasFootnotePlugin = true;
            }
          },
        },
      },
    };
  },
});

/**
 * Footnote - Block node representing [^id]: content at the bottom.
 * Parses from both markdown-it's <li> and our own <div> renders.
 */
export const Footnote = Node.create({
  name: 'footnote',
  group: 'block',
  content: 'block+',
  defining: true,
  isolating: true,

  addAttributes() {
    return {
      id: {
        default: '1',
        parseHTML: element => {
          const id = element.getAttribute('id');
          const fnId = element.getAttribute('data-footnote-id');
          if (id && id.startsWith('fn')) {
            return id.substring(2);
          }
          if (fnId) return fnId;
          return '1';
        },
      },
    };
  },

  parseHTML() {
    return [
      // From markdown-it: <li id="fn1" class="footnote-item">
      {
        tag: 'li.footnote-item',
        priority: 200,
        contentElement: (node: any) => {
          const clone = (node as HTMLElement).cloneNode(true) as HTMLElement;
          clone.querySelectorAll('.footnote-backref').forEach(a => a.remove());
          return clone;
        },
      },
      // From our own render: <div class="footnote-item" data-footnote-id="1">
      {
        tag: 'div.footnote-item',
        priority: 200,
        contentElement: 'div.footnote-content',
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return [
      'div',
      mergeAttributes(HTMLAttributes, {
        class: 'footnote-item',
        'data-footnote-id': HTMLAttributes.id,
      }),
      ['span', { class: 'footnote-label' }, `${HTMLAttributes.id}.`],
      ['div', { class: 'footnote-content' }, 0],
    ];
  },

  addStorage() {
    return {
      markdown: {
        serialize(state: any, node: any) {
          state.write(`[^${node.attrs.id}]: `);
          // Get plain text content, ignoring backref artifacts
          const textParts: string[] = [];
          node.descendants((child: any) => {
            if (child.isText) {
              const cleaned = child.text?.replace(/↩︎/g, '');
              if (cleaned) textParts.push(cleaned);
            }
            return true;
          });
          const text = textParts.join('').trim();
          if (text) state.write(text);
          state.write('\n');
        },
      },
    };
  },
});

/**
 * FootnoteContainer - Captures <ol class="footnotes-list"> from markdown-it
 * and our own <div class="footnotes-section">.
 * Does NOT match <section class="footnotes"> - that element is left unmatched
 * so ProseMirror treats it as transparent and parses its children.
 * Serializes to nothing itself, just passes through children.
 */
export const FootnoteContainer = Node.create({
  name: 'footnoteContainer',
  group: 'block',
  content: 'footnote+',
  defining: true,

  parseHTML() {
    return [
      // Only match the <ol>, NOT the <section> wrapper
      {
        tag: 'ol.footnotes-list',
        priority: 250, // Higher than default orderedList
      },
      // Our own rendered output
      {
        tag: 'div.footnotes-section',
        priority: 250,
      },
    ];
  },

  renderHTML() {
    return ['div', { class: 'footnotes-section' }, 0];
  },

  addStorage() {
    return {
      markdown: {
        serialize(state: any, node: any) {
          // Transparent - just render children
          state.renderContent(node);
        },
      },
    };
  },
});
